require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - "bin/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "logdash-*.gem"
  SuggestExtensions: false

Capybara:
  Enabled: false

FactoryBot:
  Enabled: false

Capybara/RSpec/PredicateMatcher:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "test/**/*"
    - "ruby-sdk.gemspec"

Metrics/ModuleLength:
  Max: 150

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 26

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10

Metrics/MethodLength:
  Exclude:
    - "lib/logdash/metrics.rb"
